blank_issues_enabled: false
contact_links:
  - name: Want to contribute?
    url: https://github.com/YourLGTVArtGallery/YourLGTVArtGallery.github.io/blob/main/CONTRIBUTING.md
    about: Interested in helping build TV Art? Here's how to reach us.
